config/routes.rb
RPI187Rails3::Application.routes.draw do

  resources :reports
  resources :home
  resources :sessions
  resources :users
  resources :survey_users
  resources :personality_types
  resources :survey_instance
  root :to => 'home#index'
  get 'api/questions/all', :to => 'api#all_questions'
  get 'api/questions/find/:id', :to => 'api#find'
  get 'dashboard', :to => 'sessions#new', :as => 'dashboard'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'take_survey', :to => 'survey_instance#new', :as => 'take_survey'
  get 'survey_user_login', :to => 'survey_users#new', :as => 'survey_user_login'
  resources :survey_users do
    resources :survey_results
  end
  resources :surveys do
    resources :personality_types
  end
  
end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
	attr_accessible :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_answers, :survey_user_id, :survey_id
	validates_presence_of :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_user_id, :survey_id
	serialize :survey_answers, Hash
	belongs_to :survey_user
	belongs_to :survey


	def personality_type
		key = ""
		key += (total_E > total_I) ? "E" : "I"
		key += (total_S > total_N) ? "S" : "N"
		key += (total_T > total_F) ? "T" : "F"
		key += (total_J > total_P) ? "J" : "P"
		PersonalityType.where({:name => key}).first
	end
	
end

app/controllers/survey_results_controller.rb
class SurveyResultsController < ApplicationController
  layout 'survey'
  before_filter :authorize_survey_user
#  before_action :set_survey_result, :only => [:show, :edit, :update, :destroy]
  # before_action :set_user

  # GET /survey_results
  # GET /survey_results.json
  def index
    @survey_results = SurveyResult.where({:survey_user_id => survey_user.id})
  end

  # GET /survey_results/1
  # GET /survey_results/1.json
  def show
  end

  # GET /survey_results/new
  def new
    @survey_result = SurveyResult.new
  end

  # GET /survey_results/1/edit
  def edit
  end

  # POST /survey_results
  # POST /survey_results.json
  def create
    # #@survey_result = SurveyResult.new(survey_result_params)
    # @survey_result = SurveyResult.new(params[:survey_result])
    # @survey_result.survey_user_id = survey_user.id
    # @survey_result.survey_id = 1

    # respond_to do |format|
    #   if @survey_result.save
    #     format.html { redirect_to user_survey_results_url, notice: 'Survey result was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @survey_result }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @survey_result.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /survey_results/1
  # PATCH/PUT /survey_results/1.json
  def update
    # respond_to do |format|
    #   #if @survey_result.update(survey_result_params)
    #   if @survey_result = SurveyResult.new(params[:survey_result])
    #     format.html { redirect_to user_survey_results_url(survey_user,@survey_result), notice: 'Survey result was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @survey_result.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /survey_results/1
  # DELETE /survey_results/1.json
  def destroy
    # @survey_result.destroy
    # respond_to do |format|
    #   format.html { redirect_to user_survey_results_url(survey_user,@survey_results) }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_result
      @survey_result = SurveyResult.find(params[:id])
    end
    # def set_user
    #   @survey_user = survey_user
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def survey_result_params
    #   params.require(:survey_result).permit(:survey_id, :user_id, :total_E, :total_I, :total_S, :total_N, :total_T, :total_F, :total_J, :total_P, :survey_answers)
    # end
end

app/helpers/survey_results_helper.rb
module SurveyResultsHelper
end

app/views/survey_results/index.html.erb
<h1>Listing survey_results</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Indicators</th>
<!--       <th>E</th>
      <th>I</th>
      <th>S</th>
      <th>N</th>
      <th>T</th>
      <th>F</th>
      <th>J</th>
      <th>P</th> -->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_results.each do |survey_result| %>
      <tr>
        <td><%= survey_result.personality_type.title %></td>
        <td><%= survey_result.personality_type.name %></td>
<!--         <td><%= survey_result.total_E %></td>
        <td><%= survey_result.total_I %></td>
        <td><%= survey_result.total_S %></td>
        <td><%= survey_result.total_N %></td>
        <td><%= survey_result.total_T %></td>
        <td><%= survey_result.total_F %></td>
        <td><%= survey_result.total_J %></td>
        <td><%= survey_result.total_P %></td> -->
        <td><%= link_to 'Show', survey_user_survey_result_path(survey_user,survey_result) %></td>
        <td><%= link_to 'Edit', edit_survey_user_survey_result_path(survey_user,survey_result) %></td>
        <td><%= link_to 'Destroy', survey_user_survey_result_path(survey_user,survey_result), :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/survey_results/show.html.erb
<h3 style="text-align:center">
  <%= @survey_result.personality_type.title %>
</h3><hr style="width:100%"/>
  <p>
  <%= @survey_result.personality_type.message %>
</P>
<div class="row">
	<div class="small-8 small-centered columns text-center">
		<%= link_to 'Done!', logout_path, :class =>"radius button" %>
	</div>
</div>