config/routes.rb
RPI187Rails3::Application.routes.draw do

  resources :reports
  resources :home
  resources :sessions
  resources :users
  resources :survey_users
  resources :personality_types
  resources :survey_instance
  root :to => 'home#index'
  get 'api/questions/all', :to => 'api#all_questions'
  get 'api/questions/find/:id', :to => 'api#find'
  get 'dashboard', :to => 'sessions#new', :as => 'dashboard'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'take_survey', :to => 'survey_instance#new', :as => 'take_survey'
  get 'survey_user_login', :to => 'survey_users#new', :as => 'survey_user_login'
  resources :survey_users do
    resources :survey_results
  end
  resources :surveys do
    resources :personality_types
  end
  
end

app/controllers/personality_types_controller.rb
class PersonalityTypesController < ApplicationController
  layout 'profile'
  before_filter :authorize, :except => [:show]
  #before_action :set_personality_type, :only => [:show, :edit, :update, :destroy]
  # before_action :set_survey

  # GET /personality_types
  # GET /personality_types.json
  def index
    @personality_types = PersonalityType.all
  end

  # GET /personality_types/1
  # GET /personality_types/1.json
  def show
    @personality_type = PersonalityType.find(params[:id])
  end

  # GET /personality_types/new
  def new
    @personality_type = PersonalityType.new
  end

  # GET /personality_types/1/edit
  def edit
    @personality_type = PersonalityType.find(params[:id])
  end

  # POST /personality_types
  # POST /personality_types.json
  def create
    #@category = PersonalityType.new(category_params)
    @personality_type = PersonalityType.new(params[:personality_type])
    respond_to do |format|
      if @personality_type.save
        format.html { redirect_to survey_personality_types_url(@survey,@personality_type), :notice => 'PersonalityType was successfully created.' }
        format.json { render :action => 'show', :status => :created, :location => @personality_type }
      else
        format.html { render :action => 'new' }
        format.json { render :json => @personality_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personality_types/1
  # PATCH/PUT /personality_types/1.json
  def update
    @personality_type = PersonalityType.find(params[:id])
    respond_to do |format|
      if @personality_type.update_attributes(params[:personality_type])
        format.html { redirect_to personality_types_url, :notice => 'PersonalityType was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @personality_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personality_types/1
  # DELETE /personality_types/1.json
  def destroy
    @personality_type.destroy
    respond_to do |format|
      format.html { redirect_to survey_personality_types_url(@survey) }
      format.json { head :no_content }
    end
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_personality_type
  #     @personality_type = PersonalityType.find(params[:id])
  #   end

  #   def set_survey
  #     @survey = Survey.find(params[:survey_id])
  #   end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def category_params
     # params.require(:category).permit(:name, :title, :message)
    #end
end

app/views/personality_types/_form.html.erb
<%= form_for @personality_type do |f| %>
  <% if @personality_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personality_type.errors.count, "error") %> prohibited this personality_type from being saved:</h2>

      <ul>
      <% @personality_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4><%= f.label 'Indicator' %></h4>
    <%= f.text_field :name , :style => "width:80px"%>
  </div>
  <div class="field">
    <h4><%= f.label :title %></h4>
    <%= f.text_field :title, :style => "width:400px" %>
  </div>
  <div class="field">
    <h4><%= f.label 'Video URL'%></h4>
    <%= f.text_field :video_url, :style => "width:600px" %>
  </div>
  <div class="field">
    <h4><%= f.label 'Public Description' %></h4>
    <%= f.text_area :public_description, :style => "width:100%; height:400px" %>
  </div><br/>
  <div class="field">
    <h4><%= f.label 'Private Description' %></h4>
    <%= f.text_area :private_description, :style => "width:100%; height:400px" %>
  </div>
<!--   <div class="actions">
    <%= f.submit %>
  </div> -->
  <br/>
  <a href="javascript:$('form').submit()" class="radius button success">Save</a>
<% end %>

app/views/personality_types/_profile.html.erb
<div class="row">
      <!-- Left Arrow -->
    <div class="floating-left-arrow hide-for-small">
        <a href="#"><img src="/img/profile/left-arrow.png" /></a>
    </div>
    <!-- End Left Arrow -->

    <!-- Right Arrow -->
    <div class="floating-right-arrow hide-for-small">
        <a href="#"><img src="/img/profile/right-arrow.png" /></a>
    </div>
    <!-- End Right Arrow -->
  <div class="large-4 large-centered columns" style="margin-bottom: 100px">
    <img src='/img/types_400/<%= "#{ @personality_type.name }.png" %>' />
  </div>
</div>

app/views/personality_types/edit.html.erb
<script type="text/javascript" src="/javascripts/tinymce.min.js"></script>

<div class="row">
<div class="lage-10 columns">
<%= render 'form' %>
<%= link_to 'Show', personality_type_path(@personality_type), :class => "radius button" %> 
<%= link_to 'Back', personality_types_path, :class => "radius button" %>
</div>
</div>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: "preview",
    plugins: "table",
    toolbar: "undo redo | styleselect | bold italic | link image | hr | table | preview"
 });
</script>

app/views/personality_types/index.html.erb
<div class="row">
  <div class="large-8 large-centered columns">
<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personality_types.each do |personality_type| %>
      <tr>
        <td><%= personality_type.name %></td>
        <td><%= personality_type.title %></td>
        <td><%= link_to 'Show', personality_type_path(personality_type) , :class => "tiny radius button" %></td>
        <td><%= link_to 'Edit', edit_personality_type_path(personality_type), :class => "tiny radius button" %></td>
        <td><%= link_to 'Destroy', personality_type_path(personality_type), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "tiny radius button alert" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="large-8 large-centered columns text-right">
<%= link_to 'New Personality Type', new_personality_type_path, :class => "radius button" %>

</div>
</div>

app/views/personality_types/new.html.erb
<div class="row">
<div class="lage-10 columns">
<%= render 'form' %>
<%= link_to 'Back', personality_types_path, :class => "radius button" %>
</div>
</div>

app/views/personality_types/show.html.erb
<% title "RPI | #{@personality_type.title}" %>

<div  style="background-color: #EAEEEE; border-top:2px solid #FFF; border-bottom: 1px solid #FFF; height:137px; margin-bottom:50px">

    <!-- Find Your RPI Button -->
    <div class="floating-personality-title-background hide-for-small">
        <img src="/img/profile/title-banner.png" />
    </div>
    <!-- End Button -->

        <!-- Find Your RPI Button -->
    <div class="floating-personality-title hide-for-small">
        <span><%= @personality_type.title %></span>
    </div>
    <!-- End Button -->

    <!-- Find Your RPI Button -->
    <div class="floating-find-your-rpi">
        <a href="/take_survey"><img src="/img/profile/find-your-rpi.png" /></a>
    </div>
    <!-- End Button -->
    <div class="row">
      <div class="large-12 large-centered columns text-center fixed-personality-title">
        <span><%= @personality_type.title %></span>
      </div>
    </div>
</div>

<div class="row">
	<div class="large-8 large-centered columns">
		<span class="public_description"><%= @personality_type.public_description.html_safe %></span>
	</div>
</div><br/>
<% if survey_user || current_user %>
  <div class="row">
    <div class="large-8 large-centered columns">
      <%= @personality_type.private_description.html_safe %><hr/>
    </div>
  </div><br/>
<% end %>

<div class="row">
	<div class="large-8 large-centered columns text-center social">
		<a  href="#" onclick="window.open(
      'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
      'facebook-share-dialog', 
      'width=626,height=436'); 
    return false;">
  <img src="/img/profile/facebook-share.png" /></a>
  <a href="https://twitter.com/share"><img src="/img/profile/twitter-share.png" /></a>
	</div>
</div><br />