config/routes.rb
RPI187Rails3::Application.routes.draw do

  resources :reports
  resources :home
  resources :sessions
  resources :users
  resources :survey_users
  resources :personality_types
  resources :survey_instance
  root :to => 'home#index'
  get 'api/questions/all', :to => 'api#all_questions'
  get 'api/questions/find/:id', :to => 'api#find'
  get 'dashboard', :to => 'sessions#new', :as => 'dashboard'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'take_survey', :to => 'survey_instance#new', :as => 'take_survey'
  get 'survey_user_login', :to => 'survey_users#new', :as => 'survey_user_login'
  resources :survey_users do
    resources :survey_results
  end
  resources :surveys do
    resources :personality_types
  end
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id, :category
  belongs_to :question
end

app/models/personality_type.rb
class PersonalityType < ActiveRecord::Base
	attr_accessible :name, :title, :public_description, :private_description, :video_url
	belongs_to :survey
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :survey_id, :answers_attributes
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, :allow_destroy => true
end

app/models/report.rb
class Report < ActiveRecord::Base

	def indicator_totals	
		SurveyUser.count({:group => "personality_type", :order => "count_all DESC"}).to_hash
	end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes, :surveys_attributes
  has_many :questions
  has_many :personality_types
  accepts_nested_attributes_for :questions, :allow_destroy => true

  def get_question(question_number)
  	  		
		survey = Array.new
	  question = self.questions.find(question_number)
		survey << Hash.new
		survey[0][:question] =  question.content
		survey[0][:answers] = Array.new
		question.answers.each do |answer|
			survey[0][:answers] << {
					:content => answer.content,
					:category => answer.category
				}
		end
		survey
  end

  def all_questions
  	  		
  	survey = Array.new

  	  self.questions.each_with_index do |question,index|
  		survey[index+1] = Hash.new
  		survey[index+1][:question] =  question.content
  		survey[index+1][:answers] = Array.new
  		question.answers.each do |answer|
  			survey[index+1][:answers] << {
  					:content => answer.content,
  					:category => answer.category
  				}
  		end
  	end
    survey
  end

end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
	attr_accessible :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_answers, :survey_user_id, :survey_id
	validates_presence_of :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_user_id, :survey_id
	serialize :survey_answers, Hash
	belongs_to :survey_user
	belongs_to :survey


	def personality_type
		key = ""
		key += (total_E > total_I) ? "E" : "I"
		key += (total_S > total_N) ? "S" : "N"
		key += (total_T > total_F) ? "T" : "F"
		key += (total_J > total_P) ? "J" : "P"
		PersonalityType.where({:name => key}).first
	end
	
end

app/models/survey_user.rb
class SurveyUser < ActiveRecord::Base
	attr_accessible :first_name, :last_name, :company, :title, :email, :phone, :survey_results_attributes
	validates_presence_of :email
	validates_format_of :email, :with => /.+@.+\..+/i
	validates_presence_of :first_name
	has_many :survey_results

	def self.to_csv(options = {})
	  FasterCSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |survey_user|
	      csv << survey_user.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.search(search)
	  if search
	    where( 'email LIKE ? or first_name LIKE ? or last_name LIKE ? or personality_type like ? or id like  ? or gender like ?', 
	    	"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" )
	  else
	    scoped
	  end
	end

	def account_created
		Time.parse(created_at.to_s).strftime("%m/%d/%Y")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	attr_accessible :email, :password, :password_confirmation, :survey_results_attributes
	validates_uniqueness_of :email
	has_many :survey_results
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

	before_filter :authorize_survey_user

	def all_questions
    	questions = Survey.first.all_questions
	    respond_to do |format|
	      format.json { render :json => questions }
	      format.xml { render :xml => questions }
	  	end
	end

	def find
		question_number = params[:id]
		questions = Survey.first.get_question(question_number)
		respond_to do |format|
	      format.json { render :json => questions }
	      format.xml { render :xml => questions }
	  	end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@personalty_types = PersonalityType.all
	end
	
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'survey'
	def index
		@report = Report.new
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout 'survey'
  before_filter :authorize

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @survey }
    end
  end

  def new
    @survey = Survey.new
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def create
    @survey = Survey.new(params[:survey])
    if @survey.save
      redirect_to @survey, :notice => "Successfully created survey."
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to @survey, :notice => "Successfully updated survey."
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, :notice => "Successfully destroyed survey."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authorize

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    session[:user_id] = @user.id
	    redirect_to root_url, :notice => "Thank you for signing up!"
	  else
	    render "new"
	  end
	end

	def show 
	end

	def index
	end
	
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', :class => "add_fields", :data => {:id => id, :fields => fields.gsub("\n", "")})
  end

  def title(page_title)
  	content_for(:title) { page_title }
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/survey_results_helper.rb
module SurveyResultsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/index.html.erb
<div class="row">
	<div class="large-10 large-centered columns text-center">
		<h4>Personality Type Distribution</h4>
		<canvas id="personalityDistribution" width="800px" height="400"></canvas>
	</div>
</div>

<script src="/javascripts/Chart.js"></script>
<script>
var data = {
	labels : <%= @report.indicator_totals.keys.to_json.html_safe %>,
	datasets : [

		{
			fillColor : "#69D2E7",
			strokeColor : "#F38630",
			data : <%= @report.indicator_totals.values.to_json.html_safe %>
		}
	]
}
var options = null;
var ctx = document.getElementById("personalityDistribution").getContext("2d");
new Chart(ctx).Bar(data,options);
</script>

app/views/surveys/_answer_fields.html.erb
<fieldset>
    <%= f.label :answer, "Answer" %>
  <%= f.text_field :content %>
  <%= f.label :category, "Category" %>
  <%= f.text_field :category %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', :class => "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<div class="row">
  <div class="large-12 columns">
  <%= form_for @survey do |f| %>
    <% if @survey.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
        <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<fieldset>
  <legend>Survey Name</legend>
      <%= f.text_field :name %>
</fieldset>
    
    <%= f.fields_for :questions do |builder| %>
      <%= render 'question_fields', :f => builder %>
    <% end %>
    <%= link_to_add_fields "Add Question", f, :questions %>
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

app/views/surveys/_question_fields.html.erb
<fieldset>
<legend>Question</legend>  
  <%= f.text_area :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', :f => builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/surveys/edit.html.erb
<%= render "form" %>

app/views/surveys/index.html.erb
<br/>
<div class="row">
	<div class="large-12  columns">
	<% @surveys.each do |survey| %>
	<div class="row">
		<div class="large-4 columns">
	    	<%= link_to survey.name, survey %>
		</div>
		<div class="large-4 columns">
	    	<%= pluralize(survey.questions.size, "Question") %>
		</div>
		<div class="large-4 columns">
			<%= link_to 'Edit', edit_survey_path(survey), :class => "small radius button" %>
		</div>
	</div>
	<% end %><br/>
	<div class="row">
		<div class="large-12 columns ">
		<%= link_to 'New Survey', new_survey_path, :class =>"small radius button" %>
		</div>
	</div>
</div>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "form" %>

app/views/surveys/show.html.erb
<div class="row">
<div class="large-12 columns">
<h1><%= @survey.name %></h1>

<ol class="questions">
<% @survey.questions.each do |question| %>
  <li>
    <%= "#{question.id}. #{question.content}" %>
    <ol class="answers">
      <% question.answers.each do |answer| %>
        <li><%= answer.content %> (<%= answer.category %>)</li>
      <% end %>
    </ol>
  </li>
<% end %>
</ol>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back to Surveys', surveys_path %>
</div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>