config/routes.rb
RPI187Rails3::Application.routes.draw do

  resources :reports
  resources :home
  resources :sessions
  resources :users
  resources :survey_users
  resources :personality_types
  resources :survey_instance
  root :to => 'home#index'
  get 'api/questions/all', :to => 'api#all_questions'
  get 'api/questions/find/:id', :to => 'api#find'
  get 'dashboard', :to => 'sessions#new', :as => 'dashboard'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'take_survey', :to => 'survey_instance#new', :as => 'take_survey'
  get 'survey_user_login', :to => 'survey_users#new', :as => 'survey_user_login'
  resources :survey_users do
    resources :survey_results
  end
  resources :surveys do
    resources :personality_types
  end
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id, :category
  belongs_to :question
end

app/models/personality_type.rb
class PersonalityType < ActiveRecord::Base
	attr_accessible :name, :title, :public_description, :private_description, :video_url
	belongs_to :survey
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :survey_id, :answers_attributes
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, :allow_destroy => true
end

app/models/report.rb
class Report < ActiveRecord::Base

	def indicator_totals	
		SurveyUser.count({:group => "personality_type", :order => "count_all DESC"}).to_hash
	end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes, :surveys_attributes
  has_many :questions
  has_many :personality_types
  accepts_nested_attributes_for :questions, :allow_destroy => true

  def get_question(question_number)
  	  		
		survey = Array.new
	  question = self.questions.find(question_number)
		survey << Hash.new
		survey[0][:question] =  question.content
		survey[0][:answers] = Array.new
		question.answers.each do |answer|
			survey[0][:answers] << {
					:content => answer.content,
					:category => answer.category
				}
		end
		survey
  end

  def all_questions
  	  		
  	survey = Array.new

  	  self.questions.each_with_index do |question,index|
  		survey[index+1] = Hash.new
  		survey[index+1][:question] =  question.content
  		survey[index+1][:answers] = Array.new
  		question.answers.each do |answer|
  			survey[index+1][:answers] << {
  					:content => answer.content,
  					:category => answer.category
  				}
  		end
  	end
    survey
  end

end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
	attr_accessible :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_answers, :survey_user_id, :survey_id
	validates_presence_of :total_E, :total_I, :total_S, :total_N, :total_T,
	 				:total_F, :total_J, :total_P, :survey_user_id, :survey_id
	serialize :survey_answers, Hash
	belongs_to :survey_user
	belongs_to :survey


	def personality_type
		key = ""
		key += (total_E > total_I) ? "E" : "I"
		key += (total_S > total_N) ? "S" : "N"
		key += (total_T > total_F) ? "T" : "F"
		key += (total_J > total_P) ? "J" : "P"
		PersonalityType.where({:name => key}).first
	end
	
end

app/models/survey_user.rb
class SurveyUser < ActiveRecord::Base
	attr_accessible :first_name, :last_name, :company, :title, :email, :phone, :survey_results_attributes
	validates_presence_of :email
	validates_format_of :email, :with => /.+@.+\..+/i
	validates_presence_of :first_name
	has_many :survey_results

	def self.to_csv(options = {})
	  FasterCSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |survey_user|
	      csv << survey_user.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.search(search)
	  if search
	    where( 'email LIKE ? or first_name LIKE ? or last_name LIKE ? or personality_type like ? or id like  ? or gender like ?', 
	    	"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" )
	  else
	    scoped
	  end
	end

	def account_created
		Time.parse(created_at.to_s).strftime("%m/%d/%Y")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	attr_accessible :email, :password, :password_confirmation, :survey_results_attributes
	validates_uniqueness_of :email
	has_many :survey_results
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

	before_filter :authorize_survey_user

	def all_questions
    	questions = Survey.first.all_questions
	    respond_to do |format|
	      format.json { render :json => questions }
	      format.xml { render :xml => questions }
	  	end
	end

	def find
		question_number = params[:id]
		questions = Survey.first.get_question(question_number)
		respond_to do |format|
	      format.json { render :json => questions }
	      format.xml { render :xml => questions }
	  	end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@personalty_types = PersonalityType.all
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authorize

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    session[:user_id] = @user.id
	    redirect_to root_url, :notice => "Thank you for signing up!"
	  else
	    render "new"
	  end
	end

	def show 
	end

	def index
	end
	
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', :class => "add_fields", :data => {:id => id, :fields => fields.gsub("\n", "")})
  end

  def title(page_title)
  	content_for(:title) { page_title }
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin.html.erb
<% if current_user %>
  <div class="row">
    <div class="large-12 large-centered text-center columns">
      <%= link_to "<i class=\"general foundicon-edit\"></i> RPI Questions".html_safe, edit_survey_path(1), :class => "radius button" %>
      <%= link_to "<i class=\"general foundicon-smiley\"></i> Personality Types".html_safe, personality_types_path, :class => "radius button" %>
      <%= link_to "<i class=\"general foundicon-address-book\"></i> User Database".html_safe, survey_users_path, :class => "radius button" %>
      <%= link_to "<i class=\"general foundicon-graph\"></i> Reports".html_safe, reports_path, :class => "radius button" %>
      <%= link_to "<i class=\"general foundicon-unlock\"></i> Logout".html_safe, logout_path, :class => "radius button alert" %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <div id="layout_footer">

    <div id="footer">

      <!-- Footer Large -->
      <footer class="hide-for-small">
        <div class="row">
          <div class="large-6 columns bottom-nav" style="margin-top: 30px">
            <ul class="inline-list left">
              <li><a href="/take_survey"><img src="/img/footer/get-started.png"/></a></li>
              <li><span style="margin-top: 6px">&copy; BGI, LLC All Rights Reserved</span></li>
            </ul>
          </div>
          <div class="large-6 columns bottom-nav">
            <ul class="inline-list right">
              <li><a href="#" data-reveal-id="privacy_policy" style="margin-top:6px">PRIVACY</a></li>
              <li><a href="https://www.facebook.com/BiggerGains" target="_blank"><img src="/img/footer/facebook.png"/></a></li>
              <li><a href="http://twitter.com/kennsullivan" target="_blank" ><img src="/img/footer/twitter.png"/></a></li>
              <li><a href="http://www.linkedin.com/pub/kenn-sullivan/2/191/996" target="_blank"><img src="/img/footer/linkedin.png"/></a></li>
              <li><a href="http://www.youtube.com/user/BiggerGainsTV" target="_blank"><img src="/img/footer/youtube.png"/></a></li>
            </ul>
          </div>
        </div>
      </footer>
      <!-- End Footer Large -->

      <!-- Footer Small -->
      <footer class="show-for-small">
        <div class="row">
          <div class="large-12 large-centered columns text-center bottom-nav" style="margin-top: 50px">
              <a href="/take_survey"><img src="/img/footer/get-started.png"/></a>
          </div>
        </div>
      </footer>
      <!-- End Footer Small -->

    </div>
  </div> <!-- layout footer -->

</div> <!-- layout -->

  <div id="privacy_policy" class="reveal-modal hide-for-small">
    <%= render :partial => 'layouts/privacy' %>
  </div>
  <a class="close-reveal-modal hide-for-small">&#215;</a>
</body>
</html>

app/views/layouts/_header.html.erb
  <!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= yield(:title) || "RPI | Bigger Gains International" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div id="layout">

  <div  class="background-gradient">
    <%= render :partial => 'layouts/nav' %>
    <%= render :partial => 'home/video' %>
  </div>

app/views/layouts/_nav.html.erb
<!-- Large header and nav -->
<div class="row hide-for-small" style="margin-bottom:20px">
  <div class="large-4 columns top-nav">
    <div class="inline-list left">
      <li><a href="/take_survey"><img src="/img/header/get_started.png" /></a></li>
    </div>
  </div>
  <div class="large-4 columns top-logo">
    <a href="/"><img src="/img/header/rpi_logo.png" /></a>
  </div>
  <div class="large-4 columns top-nav">
    <ul class="inline-list right">
      <li><a href="https://www.facebook.com/BiggerGains" target="_blank" ><img src="/img/header/facebook.png"/></a></li>
      <li><a href="http://twitter.com/kennsullivan" target="_blank" ><img src="/img/header/twitter.png"/></a></li>
      <li><a href="http://www.linkedin.com/pub/kenn-sullivan/2/191/996" target="_blank" ><img src="/img/header/linkedin.png"/></a></li>
      <li><a href="http://www.youtube.com/user/BiggerGainsTV" target="_blank" ><img src="/img/header/youtube.png"/></a></li>
    </ul>
  </div>
</div>
<!-- End Large header -->

<!-- Small Header -->
<div class="row show-for-small">
  <div class="large-4 large-centered text-center columns top-logo">
    <a href="/"><img src="/img/header/rpi_logo.png" /></a>
  </div>
</div>
<!-- End Small Header -->

app/views/layouts/_profile_header.html.erb
  <!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= yield(:title) || "RPI | Bigger Gains International" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div id="layout">

  <div  class="background-gradient">
    <%= render :partial => 'layouts/nav' %>
    <%= render :partial => 'personality_types/profile' %>
  </div>

app/views/layouts/_survey_footer.html.erb
<!-- Survey Footer -->

  </body>
</html>

app/views/layouts/_survey_header.html.erb
  <!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= yield(:title) || "RPI | Bigger Gains International" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div id="layout">

  <div  class="background-gradient">
    <%= render :partial => 'layouts/nav' %>
  </div>

app/views/layouts/application.html.erb
<%= render :partial => 'layouts/header' %>
<%= yield %>
<%= render :partial => 'layouts/footer' %>

app/views/layouts/profile.html.erb
<%= render :partial => 'layouts/profile_header' %>
<%= render :partial => 'layouts/admin' %>
<%= yield %>
<%= render :partial => 'layouts/footer' %>

app/views/layouts/survey.html.erb
<%= render :partial => 'layouts/survey_header' %>
<%= render :partial => 'layouts/admin' %>
<%= yield %>